rate: 15
pid_list: [{name: "turret_pid",
            feedback_topic: "/turret/feedback",
            setpoint_topic: "/turret/setpoint",
            control_topic: "/turret/cmd_vel",
            control_max: 50,
            control_min: -50,
            kp: 0.25,
            ki: 0,
            kd: 0,
            kf: 0}]