rate: 15
pid_list: [{name: "turret_pid",
            feedback_topic: "/turret/feedback",
            setpoint_topic: "/turret/setpoint",
            control_topic: "/turret/cmd_vel",
            control_max: 15,
            control_min: -15,
            kp: 0.05,
            ki: 0,
            kd: 0,
            kf: 0}]